disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Richard Burgoyne"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "https://avatars.githubusercontent.com/u/200693696?v=4"
  secondaryLogo = "https://avatars.githubusercontent.com/u/200693696?v=4"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
  name = "Richard Burgoyne"
  email = "hello@richardburgoyne.com"
  image = "https://avatars.githubusercontent.com/u/200693696?v=4"
  imageQuality = 96
  #headline = "I'm only human"
  #bio = "A little bit about you"
  links = [
    { email = "mailto:hello@richardburgoyne.com" },
    { linkedin = "https://www.linkedin.com/in/richard-burgoyne/" },   
  ]
